language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ez-plugin' ]; then cd .. && eval "mv $currentfolder generator-ez-plugin" && cd generator-ez-plugin; fi

